### ISSUE TITLE
论文上的疑惑

### ISSUE THREAD

**Issue by evi-Genius** [PingoLH/Pytorch-HarDNet#1]
您好，我在阅读您的论文的时候有点疑惑：'CIO dominates the inference time only when the computational density, which is, the MACs over CIO (MoC) of a layer, is below a certain ratio that depends on platforms'
如果我理解的没有问题的话，这句话表示：computational density的相当于MoC低于某个ratio，而MoC的意思是 运算量/内存访问。是否意味着computational density是运算量较少的情况呢？

**Comment by PingoLH** [comment]
您好，感謝您的提問。這是說當MoC低於一個ratio時, performance is memory bound,  而高於這個ratio則是compute bound。若network中每個layer的MoC都很低的時候，可以發現inference time與CIO是成正比的。因此我們盡量提高每一layer的 MoC，避免memory bound的狀況發生。

**Comment by evi-Genius** [comment]
> 您好，感謝您的提問。這是說當MoC低於一個ratio時, performance is memory bound, 而高於這個ratio則是compute bound。若network中每個layer的MoC都很低的時候，可以發現inference time與CIO是成正比的。因此我們盡量提高每一layer的 MoC，避免memory bound的狀況發生。

谢谢您的回复，抱歉我前几天没有注意到。我还有一个问题，我理解您论文上的意思是减少shortcut和减少1×1的conv来减少CIO，前者我已经明白了，后者是否意味着可以在设计网络的时候，考虑同等计算量，用3×3代替1×1比较好？即使网络层数因此减少的情况下。

**Comment by PingoLH** [comment]
您好，關於這個問題，事實上是不一定。套用在ResNet上面您可能會發現若將1x1全部直接換成3x3並不會提升太多準確率, 減少層數而全部使用3x3則會明顯降低準確率。這個還是跟網路的結構相關。只能說我們的目標是原則上盡量不使用1x1，然後發現了一個能夠不倚賴1x1也可以有良好學習效率以及計算複雜度的結構。

**Comment by evi-Genius** [comment]
> 您好，關於這個問題，事實上是不一定。套用在ResNet上面您可能會發現若將1x1全部直接換成3x3並不會提升太多準確率, 減少層數而全部使用3x3則會明顯降低準確率。這說明了ResNet相當程度地倚賴1x1的使用。而我們的目標是原則上盡量不使用1x1，然後發現了一個能夠不倚賴1x1也可以有良好學習效率以及計算複雜度的結構。

我明白了，谢谢您的耐心解答，您的方法对于移动端设计网络的思路很有意义！
